--------------------------------------------------------------------
-- DROP TABLES
--------------------------------------------------------------------
DROP TABLE TICKET CASCADE CONSTRAINTS;

-- DROP TABLE MOUSE_DETAILS CASCADE CONSTRAINTS;
-- DROP TABLE KEYBOARD_DETAILS CASCADE CONSTRAINTS;
-- DROP TABLE TABLET_DETAILS CASCADE CONSTRAINTS;
-- DROP TABLE DISPLAY_EQUIPMENT_DETAILS CASCADE CONSTRAINTS;
-- DROP TABLE PRINTER_SCANNER_DETAILS CASCADE CONSTRAINTS;
-- DROP TABLE LAPTOP_DETAILS CASCADE CONSTRAINTS;
-- DROP TABLE DESKTOP_DETAILS CASCADE CONSTRAINTS;
-- DROP TABLE NETWORK_EQUIPMENT_DETAILS CASCADE CONSTRAINTS;

DROP TABLE IP_ADDRESS CASCADE CONSTRAINTS;

DROP TABLE ASSET CASCADE CONSTRAINTS;
DROP TABLE ASSET_TYPE CASCADE CONSTRAINTS;
DROP TABLE USER_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE USER_ROLE CASCADE CONSTRAINTS;

DROP TABLE NETWORK CASCADE CONSTRAINTS;
DROP TABLE SITE CASCADE CONSTRAINTS;
