-- A METTRE EN AVANT
CREATE USER C##CY_TECH_CERGY IDENTIFIED BY cergy123;  -- Base de donnée de Cergy
GRANT CREATE SESSION TO C##CY_TECH_CERGY;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO C##CY_TECH_CERGY;
-- A METTRE EN AVANT

-- (insérer les tables et les données dedans)