-- Création du rôle SUPER_ADMIN
CREATE ROLE SUPER_ADMIN;

-- Attribution des droits des rôles ADMIN_CERGY et ADMIN_PAU au rôle SUPER_ADMIN
GRANT ADMIN_CERGY TO SUPER_ADMIN;
GRANT ADMIN_PAU TO SUPER_ADMIN;

-- Optionnel : création d'un utilisateur et attribution du rôle SUPER_ADMIN
CREATE USER CY_TECH_ADMIN IDENTIFIED BY admin123;
GRANT SUPER_ADMIN TO super_admin;

GRANT ALL PRIVILEGES ON CY_TECH_PAU.* TO CY_TECH_ADMIN;
GRANT ALL PRIVILEGES ON CY_TECH_CERGY.* TO CY_TECH_ADMIN;